import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

<><link rel="icon" href="/favicon.png" /><link rel="apple-touch-icon" href="/icons/icon-192x192.png" /><link rel="manifest" href="/manifest.json" /><meta name="theme-color" content="#f97316" /><><link rel="manifest" href="/manifest.json" /><meta name="theme-color" content="#f97316" /></></>

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
